server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed.
  undertow:
    threads:
      worker: 64 # Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 4 # One IO thread per CPU core is a reasonable default: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    hikari: # Responsável por gerenciar o pool de conexões com o banco
      auto-commit:  false # na conexão com o banco de dados nao vai vim com auto-commit,ou seja, gerenciar o commit e o rollback manualmente  com  (spring/hibernate)
      connection-timeout: 250 # É uma configuração em milliseconds. O ideal é manter baixo para que estoure timeout logo e não prenda as threads.
      max-lifetime: 600000 # Tempo máximo que uma conexão pode ficar aberta (10 min) - security.
      maximum-pool-size: 20 # Mantemos até no máx 20 conexões com o banco de dados. O ideal é manter baixo mesmo, pois é algo custoso para o banco gerenciar. https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
      minimum-idle: 10 # Mantém o min de conexões caso nao esteja sendo muito utilizado
      pool-name: master #apenas um nome
  jpa:
      open-in-view: false # abrir uma conexão com o banco desde o controller (foi deixado falso pq manter uma conexão desde o controller é muito custoso)
      show-sql: true # printa as query sql, é bom pra troubleshooting, em prod deixa desabilitado
      hibernate:
        ddl-auto: none # diz ao hibernate se é necessário criar e atualizar o schema do banco de dados automaticamente
      properties:
        "[hibernate.dialect]": "org.hibernate.dialect.MySQL8Dialect"
        "[hibernate.generate_statistics]": false #printa estatisticas do hibernate
        "[hibernate.connection.provider_disables_autocommit]": true #
        # Para aumentar a performance ao máximo, desabilitamos o auto-commit e o open-in-view.
        # https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/



